In [2]:
import numpy as np

In [4]:
np.random.random()#here we get ramdom value from(0-1) every time we run the code

0.1317809419611875

In [11]:
np.random.seed(1)#here we are getting same value from (0-1)every time we run the command, while using seed function
np.random.random()

0.417022004702574

In [20]:
np.random.uniform(3,10)#here it generate random value between 3 and 10

3.646370163381585

In [34]:
np.random.uniform(1,100,10).reshape(5,2)# used to generate random value with certain gap or range and here 11 indicates the size

array([[47.77502876, 74.53371818],
       [20.00365175, 46.96683883],
       [23.80591803, 51.31650622],
       [21.64826285,  5.88112023],
       [52.36732571, 18.05555687]])

In [36]:
np.random.randint(1,10,15).reshape(3,5)

array([[2, 2, 9, 8, 1],
       [4, 5, 3, 1, 4],
       [6, 2, 3, 5, 4]])

In [40]:
a = np.random.randint(1,100,6)
a

array([ 9, 85, 78, 51, 80, 42])

In [42]:
np.max(a)

85

In [44]:
np.min(a)

9

In [23]:
#to return the index of the concerned value
import numpy as np
a = np.random.randint(1,100,6)
a

array([70, 92, 61, 99, 77, 68])

In [12]:
np.argmax(a)

3

In [14]:
a[np.argmax(a)]

97

In [25]:
a[a%2==1]=-1#what is does is that it will assign the -1 to the value that gives the remainder 1 when divided by 2
a

array([70, 92, -1, -1, -1, 68])

In [29]:
#this means where[condition,for true,for false]
np.where(a%2==1,-1,a)

array([70, 92, -1, -1, -1, 68])

In [31]:
a = np.random.randint(1,50,10)
a

array([40, 39, 49, 39, 24, 13,  8, 13, 11, 15])

In [33]:
a = np.sort(a)
a

array([ 8, 11, 13, 13, 15, 24, 39, 39, 40, 49])

In [37]:
np.percentile(a,25)#it means that the25% of the value in the array is less than or equal to 13

13.0